# Generated by Django 5.0 on 2023-12-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kami_workforce_airlines_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
